---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    smtp_server:      10.100.13.31
    mail_from:        Ansible Automation Platform <sysadmin@gmd.com.pe>
    mail_to:          Alexis Alvarado <aalvarado@canvia.com>
    mail_copy:        Infraestructura <rsaavedra@canvia.com>
    mail_subject:     Reporte
    mail_body:        Reporte de Aceros Arequipa
    archivoexcel1:    ReporteCapacidadesCOT1.csv
    archivoexcel2:    ReporteCapacidadesCOT4.csv
    archivoexcel3:    ReporteMensual1.csv
    archivoexcel4:    ReporteMensual2.csv
    archivoexcel5:    ReporteMensual3.csv
    archivoexcel6:    ReporteMensual4.csv
    vcenterip1:       172.23.1.29
    vcenterip2:       172.23.1.34
    vcenterip3:       172.23.8.139
    vcenterip4:       172.23.8.39
    vcusername1:      GMDSA\\aalvarado
    vcpassword1:      Por*siempre0829
    vcusername2:      cnvauto@canviacloud.com
    vcpassword2:      CnV4ut01$

  tasks:

    - name: Escribir WWNs de AIX
      shell: |
        echo "Lun Name, Group, Capacity, LUN ID" > {{ archivoexcel1 }} 
        ssh -i automation-svc-lindley -l adminrep 10.0.1.102 svcinfo lsvdisk -unit gb | grep aaq | grep -v "[[:blank:]]rc" | awk '{ print $2,$7,$8,$10 }' | tr " " "," >> {{ archivoexcel1 }}
        ssh -i automation-svc-lindley -l adminrep 10.0.1.102 svcinfo lsvdisk -unit gb | grep aaq | grep "[[:blank:]]rc" | awk '{ print $2,$7,$8,$12 }' | tr " " "," >> {{ archivoexcel1 }}
      delegate_to: localhost

    - name: Escribir WWNs de AIX
      shell: |
        echo "Lun Name, Group, Capacity, LUN ID" > {{ archivoexcel2 }}
        ssh -i automation-svc-lindley -l adminrep 10.0.65.200 svcinfo lsvdisk -unit gb | grep aaq | grep -v "[[:blank:]]rc" | awk '{ print $2,$7,$8,$10 }' | tr " " "," >> {{ archivoexcel2 }}
        ssh -i automation-svc-lindley -l adminrep 10.0.65.200 svcinfo lsvdisk -unit gb | grep aaq | grep "[[:blank:]]rc" | awk '{ print $2,$7,$8,$12 }' | tr " " "," >> {{ archivoexcel2 }}
      delegate_to: localhost

    - name: Generar reporte de VCenter COT1 
      shell: |
        ./list_vcenters.ps1 {{ vcenterip1 }} {{ vcusername1 }} {{ vcpassword1 }} > {{ archivoexcel3 }}
      delegate_to: localhost
    
    - name: Generar reporte de VCenter COT 4
      shell: |
        ./list_vcenters.ps1 {{ vcenterip2 }} {{ vcusername1 }} {{ vcpassword1 }} > {{ archivoexcel4 }}
      delegate_to: localhost

    - name: Generar reporte de VCenter COT 1 LENOVO
      shell: |
        ./list_vcenters.ps1 {{ vcenterip3 }} {{ vcusername2 }} {{ vcpassword2 }} > {{ archivoexcel5 }}
      delegate_to: localhost

    - name: Generar reporte de VCenter COT 4 LENOVO
      shell: |
        ./list_vcenters.ps1 {{ vcenterip4 }} {{ vcusername2 }} {{ vcpassword2 }} > {{ archivoexcel6 }}
      delegate_to: localhost

    - name: Convertir a excel
      script: convertidor.py
      delegate_to: localhost

    - name: Enviar reporte por correo 
      mail: 
        host: "{{ smtp_server }}" 
        port: 25 
        from: "{{ mail_from }}" 
        to: "{{ mail_to }}"
        cc: "{{ mail_copy }}"
        subject: "{{ mail_subject }}" 
        body: "{{ mail_body }}" 
        attach: 
          - "{{ archivoexcel1 }}.xlsx" 
          - "{{ archivoexcel2 }}.xlsx"
          - "{{ archivoexcel3 }}.xlsx" 
          - "{{ archivoexcel4 }}.xlsx"
          - "{{ archivoexcel5 }}.xlsx"
          - "{{ archivoexcel6 }}.xlsx"
      #delegate_to: localhost 
      run_once: True 
    