---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    smtp_server:      10.100.13.31
    mail_from:        Ansible Automation Platform <sysadmin@gmd.com.pe>
    mail_to:          Alexis Alvarado <aalvarado@canvia.com>
    mail_copy:        Infraestructura <rsaavedra@canvia.com>
    mail_subject:     Reporte
    mail_body:        Reporte de Aceros Arequipa
    archivoexcel1:    /tmp/reporte1-svc.csv
    archivoexcel2:    /tmp/reporte2-svc.csv
  
  tasks:

    - name: Escribir WWNs de AIX
      shell: ssh -i automation-svc-lindley -l adminrep 10.0.1.102 svcinfo lsvdisk -unit gb | grep aaq | awk '{ print $2,$7,$8,$10 }' | tr " " "," > /tmp/reporte1-svc.csv
      delegate_to: localhost

    - name: Escribir WWNs de AIX
      shell: ssh -i automation-svc-lindley -l adminrep 10.0.65.200 svcinfo lsvdisk -unit gb | grep aaq | awk '{ print $2,$7,$8,$10 }' | tr " " "," > /tmp/reporte2-svc.csv
      delegate_to: localhost

    - name: Enviar reporte por correo 
      mail: 
        host: "{{ smtp_server }}" 
        port: 25 
        from: "{{ mail_from }}" 
        to: "{{ mail_to }}"
        cc: "{{ mail_copy }}"
        subject: "{{ mail_subject }}" 
        body: "{{ mail_body }}" 
        attach: 
          - "{{ archivoexcel1 }}" 
          - "{{ archivoexcel2 }}" 
      # delegate_to: localhost 
      run_once: True 

    - name: 
    